### ISSUE TITLE
Fiat donation flow designs match w/ Figma

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1733]
**CU Ticket:** https://app.clickup.com/t/865bm5pu2
**Assigned To:** 
**Version:** v1.8

**Comment by abbasali1994** [comment]
Checked kado docs on 9 March and no updates have been shared on release of "post order status" feature as of now
Since this feature is a necessary element for our fiat flow design keeping this ticket in backlog for now,
also will communicate with kado team via mail to inquire on when they plan to release this feature
