### ISSUE TITLE
newer charities that have no banner seem to disappear from browser to leave a blank page.

### ISSUE THREAD

**Issue by angelprotocol-validator** [AngelProtocolFinance/angelprotocol-web-app#1839]
This loom explains it all. 

https://www.loom.com/share/d2ba956f95454caa8569ecb9466de032

and see attached image for console. 

![Screenshot 2023-02-21 at 09 13 05](https://user-images.githubusercontent.com/85955479/220300853-3660109e-c6d8-4604-afcb-9b1949ba5b6e.png)

**Comment by misicnenad** [comment]
@SovereignAndrey these charities seem to miss some data that we assume should be there, as it is required on both Registration and Edit Profile.

E.g. navigating to https://app.angelgiving.io/profile/141 (charity named "CORE Community Organized Response Effort"), we see that accessing `EndowmentProfile.categories.sdgs` is throwing an error because `categories` is undefined, which is unexpected (see [type definition](https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/master/src/types/aws/ap/index.ts#L8)), we also see that `EndowmentProfile.social_media_urls` is undefined, whereas it should always be *defined* (see [type definition](https://github.com/AngelProtocolFinance/angelprotocol-web-app/blob/master/src/types/aws/ap/index.ts#L22)).

The former is probably an issue of the charity being created before `categories.sdgs` was set as required and the latter can be addresses by ensuring on AWS side that `social_media_urls` is always defined (on the other hand its subfields are expected to not always be defined).

**Comment by misicnenad** [comment]
@SovereignAndrey can we close this or is this still to be addressed?

**Comment by SovereignAndrey** [comment]
> @SovereignAndrey can we close this or is this still to be addressed?

It's already closed.

**Comment by misicnenad** [comment]
> > @SovereignAndrey can we close this or is this still to be addressed?
> 
> It's already closed.

Ah, the page was open on my browser and was showing outdated status.
