### ISSUE TITLE
restart and create a useful hubspot export from the registration form submissions

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1880]
CU #: 8677fqxn4 - https://app.clickup.com/t/8677fqxn4
Created on: Feb 22 2023 
Original Creator: Tim Stirrup

## Description
<p>Currently, when a nonprofit signs up, I USED to get get a simple text message that creates a ticket as follows: <strong>This process seems to have stopped! </strong><br/><br/>&quot;Hey gang, Somebody has started a registration process for an organization with reference number efcfe72b-3aac-42db-bdb8-b3af1b3d184a. Email address: <a href="mailto:robertjefferson509@gmail.com" target="_blank">robertjefferson509@gmail.com</a> Phone number: not provided Please update the corresponding record in HubSpot and set follow-up tasks for 48h from now if their status hasn&#x27;t changed. wagmi&quot;<br/><br/>Which I then had to manually change a few things to get a good record. <br/><br/>what format is all the data received in and how can that be better sent across and updated? </p>

**Comment by jp-mariano** [comment]
It seems that Tim used to receive the email coming from AWS. Because when we send any email to the registrant regarding their charity application, we are also sending in tandem a team email.

To troubleshoot things, I will try to change the team email to my own angel email and check if I can receive team emails. For context the current team email set at the `env` is `support@angelgiving.io`. This should probably be changed back to `angelprotocol.io`.

---

> what format is all the data received in and how can that be better sent across and updated?

In the `registration-submit` Lambda, when a proposal is successfully created, the Lambda sends out a Discord message to the channel `#charity-applications`. After this, it also sends out a `POST` request with a payload* that contains data of the Contact Person to the HubSpot form. The URL to which the request is sent is: `https://api.hsforms.com/submissions/v3/integration/submit/24900163/e742b3a1-ab7a-4831-9d3d-77e86c34cd42`.

Payload*:
```ts
{
   fields: [ { key: "firstname", value: "Thors" } ], // array of objs with key and value pairs
   pageName: "AWS registration submitter"
}
```

Are they not receiving updates to this endpoint?

**Comment by SovereignAndrey** [comment]
It is the hubspot endpoint that they are not getting data at anymore I think. Are we able to confirm that endpoint, api key and payload return a 200/201 status?

**Comment by jp-mariano** [comment]
> It is the hubspot endpoint that they are not getting data at anymore I think. Are we able to confirm that endpoint, api key and payload return a 200/201 status?

Thanks for clarifying. I used Postman to send dummy data (payload is the same format) to the same endpoint and I got a `200 OK`. The returned payload is:
```json
{
   "inlineMessage": "Thanks for submitting the form."
}
```
