### ISSUE TITLE
AST Launchpad: Re-wired to send `create_endowment` msg to Polygon or Juno (based on wallet connected for signing)

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1910]

**Comment by ap-justin** [comment]
@SovereignAndrey, where should I send the message to create endowment in Polygon 

![Image](https://user-images.githubusercontent.com/89639563/225319672-240d88da-8d8d-4005-ad97-411334b67bd4.png)

**Comment by SovereignAndrey** [comment]
> ~~@SovereignAndrey, where should I send the message to create endowment in Polygon ?~~
> UPDATE: was lookin on repo x_x, diamon accounts is on the zip file sent on discord group
> 
> 
> 

You got it. To the Accounts diamond contract. :100:

**Comment by ap-justin** [comment]
@SovereignAndrey, whether to send to `polygon` or `juno` coudn't simply depend on the `submit` step where we check the connected wallet's `network`. In some steps like `Management`, `Maturity`, `Fees` - there are address inputs that should be validated depending on what chain it is intended to be submitted 

The solution to this is 
1. Before starting new registration, prompt user to `connect` wallet, and based on that save the intended `network`. This is a bit complicated since user might change wallet while registering where it's different than what network he started on 

2. Connecting wallet is not required but at the start of registration, user explicitly selects whether he/she wants to create endowment in `polygon` or in `juno. Then checks are done in submit. 
If user selects `polygon` at the start, he needs to connect metamask, or `keplr` otherwise

**Comment by SovereignAndrey** [comment]
> I am leaning on `2` but would like to let you know first before commiting changes

@ap-justin I think #2 makes sense too! :+1:  Having the choice would only be applicable for AST registrations, where they will have that option of Juno vs Polygon, though we should probably make sure to default the selection to a Polygon-based AST. All Charity endowments would be created on Polygon only.
