### ISSUE TITLE
Support Request 

incorrect replies/popup messages?


### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#2305]
Just bumping this message in discord up again https://discord.com/channels/834976399228010527/857111094019883010/1140594467666153492 - while that issue for me was on the staging site, I just had a new charity just successfully apply on the live site, BUT they had a popup message say their application had been rejected. can you check the reply messages on the registration flow? both live and staging?

**Comment by jp-mariano** [comment]
Based from more information given by Tim, this was encountered by endowment 185. They were trying to `submit` their registration application and were getting confused with the error pop-up as being "rejected" by AP team. The error was due to the version of `cosmjs` used in AWS which has been updated since. For reference, here's the message I sent in our Discord server: https://discord.com/channels/834976399228010527/857111094019883010/1142045624989134909
